
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmvkmlnfklivofxdbpse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtdmttbG5ma2xpdm9meGRicHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDMwNjMsImV4cCI6MjA2MjQ3OTA2M30.8yvA-ee1PQGpoq8UQtM8ekdu10bhok9JUtXNX8Ougd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
